development:
  adapter: postgresql
  database: openbound_development
  mysql2pool: 5
  encoding: utf8
  reconnect: false
  username: ob_dev
  password: ob
  host:  localhost

test:
  adapter: postgresql
  database: openbound_test
  pool: 5
  encoding: utf8
  username: ob_dev
  password: ob
  host:  localhost

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 100
