development:
  adapter: mysql2
  database: rstacks_development
  pool: 5
  encoding: utf8
  reconnect: false
  username: root
  password: 
  host:  localhost
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  database: rstacks_test
  pool: 5
  encoding: utf8
  username: root
  password: 
  host:  localhost

# This information is duplicated in /config/rubber/common/database.yml, 
# which pulls environment rubber_env variables from /config/rubber/rubber.yml. 
# These should be set to the host machine instead of hardcoded, but there they are, 
# sucka. 

production:
  adapter: mysql2
  # encoding: utf8
  # database: <%= ENV["RDS_DB_NAME"] %>
  # username: <%= ENV["RDS_USERNAME"] %>
  # password: <%= ENV["RDS_PASSWORD"] %>
  # host: <%= ENV["RDS_HOSTNAME"] %>
  # port: <%= ENV["RDS_PORT"] %>

# This should be different than production. Junk data. 
staging:
  adapter: mysql2
  # encoding: utf8
