development:
  secret_key_base: 310d01f838dcaa1f076a0b6621241076d0d551008e8d3aeceb6a285f42af0f298068072c2345575d684ae13494c6ce9bfd26198af5ce649e0aabb57d2b7f9524
  google_api_key: <%= ENV["OB_GOOGLE_API_KEY"] %>  

test:
  secret_key_base: d350b46456f7e9a0c6eba70a140ab32cdda5a0c7e163c8887e77e79e692ee83b06f038735d5a3d04014123516c73888afe688714ca0cc80c2576e8f77195cad3
 
staging: 
  secret_key_base: <%= ENV["SECRET_KEY_BASE_STAGING"] %>
  google_api_key: <%= ENV["OB_GOOGLE_API_KEY"] %>  

 # Do not keep production secrets in the repository,
 # instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_PRODUCTION"] %>
  google_api_key: <%= ENV["OB_GOOGLE_API_KEY"] %>
  google_drive_client_id: <%= ENV["GOOGLE_DRIVE_CLIENT_ID_ELSE"] %>



