production:
  solr:
    hostname: ec2-52-24-58-239.us-west-2.compute.amazonaws.com #rubber will append to this file #prod_start...
    port: 8983
    log_level: WARNING
    path: /solr/production
    # this to avoid sunspot telling solr to make solr commits after each save, which in events like uploading 7
    # pdfs at once will overheat solr and cause a MaxWarmingSearchers=5 error. Will instead rely on 
    # autoCommit configured in solrconfig.xml element <updateHandler>
    # http://stackoverflow.com/questions/7512945/how-to-fix-exceeded-limit-of-maxwarmingsearchers
    # https://github.com/sunspot/sunspot/issues/231
    # https://groups.google.com/forum/#!topic/ruby-sunspot/h_tFvDkxsI8
    auto_commit_after_request: false
    # auto_commit_after_delete_request: false
    # read_timeout: 2
    # open_timeout: 0.5

staging:
  solr:
    hostname: localhost #not true, but rubber will append to this file #prod_start...
    port: 8983
    log_level: WARNING
    path: /solr/staging
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test